# Generated by Django 6.0.4 on 2026-05-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_bio_author_natinality_remove_book_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='natinality',
            new_name='natinolity',
        ),
    ]
